# Generated by Django 3.0.6 on 2020-09-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200925_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
