# Generated by Django 3.0.6 on 2020-09-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='proilfe_pic',
            new_name='profile_pic',
        ),
    ]
