# Generated by Django 3.0.6 on 2020-09-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200930_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='.profile_pic'),
        ),
    ]
