# Generated by Django 3.0.6 on 2020-10-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200930_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='aboutme',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pic'),
        ),
    ]
